import "./globals.css";
import Header from "./components/layout/Header";
import { Nunito_Sans, Open_Sans, Quicksand } from "next/font/google";
import ScrollTop from "../../public/icons/SVG/scroll-totop";
import ScrolltoTop from "./components/Sections/ScrollToTop";

export const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["700"], // bold for titles
  variable: "--font-nunito",
  adjustFontFallback: false, // Fixes: Failed to find font override values error
});

export const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"], // regular for body
  variable: "--font-open-sans"
});

export const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["500"], // medium for accents
  variable: "--font-quicksand"
});

export const metadata = {
  title: "VexAura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`aurora-top ${nunito.variable} ${openSans.variable} ${quicksand.variable}`}
      >
        <main className="main-content">
          {children}
          <footer
            className="relative bottom-0 flex gap-[24px] left-[0px] text-white flex-wrap items-center justify-center w-full py-6"
          > 
            <ScrolltoTop/>
            Habiba Taliby © 2025
          </footer>
        </main>
      </body>
    </html>
  );
}