import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import {ThemeProvider} from "./components/AppContext";
import { Nunito_Sans, Open_Sans, Quicksand } from "next/font/google";

export const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["700"], // bold for titles
  variable: "--font-nunito"
});

export const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"], // regular for body
  variable: "--font-open-sans"
});

export const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["500"], // medium for accents
  variable: "--font-quicksand"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VexAura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth ">

       <body
       className={`aurora-top ${nunito.variable} ${openSans.variable} ${quicksand.variable} ${geistSans.variable} ${geistMono.variable}`}
      >
      <ThemeProvider>
        
        <main className="relative mx-auto ">

          <Header />
          {children}
         
         
          <footer
            className="absolute top-[100%] flex gap-[24px] left-[0px] text-white flex-wrap items-center justify-center w-full p-6 mt-10"
          >
            VexAura © 2025
          </footer>
        </main>



      
      </ThemeProvider>
     </body>
    </html>
  );
}
